SigortaApp/Areas/Admin/Controllers/MessageController.cs
using SigortaApp.BL.Abstract;
using SigortaApp.BL.Concrete;
using SigortaApp.Entity.Concrete;
using SigortaApp.DAL.Concrete;
using SigortaApp.DAL.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace SigortaApp.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MessageController : Controller
    {
        private readonly IMessage2Service _message2Service;
        private readonly Context _context;

        public MessageController(IMessage2Service message2Service, Context context)
        {
            _message2Service = message2Service;
            _context = context;
        }

        [Authorize(Roles ="Admin")]
        public IActionResult InBox()
        {
            var username = User.Identity.Name;
            var usermail = _context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = _context.Writers.Where(w => w.Mail == usermail).Select(y => y.Id).FirstOrDefault();
            var values = _message2Service.GetInboxListByWriter(writerId);
            return View(values);
        }
        public IActionResult SendBox()
        {
            var username = User.Identity.Name;
            var usermail = _context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = _context.Writers.Where(w => w.Mail == usermail).Select(y => y.Id).FirstOrDefault();
            var values = _message2Service.GetSendboxListByWriter(writerId);
            return View(values);
        }
        [HttpGet]
        public IActionResult ComposeMessage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ComposeMessage(Message2 p)
        {
            var username = User.Identity.Name;
            var usermail = _context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = _context.Writers.Where(w => w.Mail == usermail).Select(y => y.Id).FirstOrDefault();
            p.SenderId = writerId;
            p.ReveiverId = 8;//ALICI AYARLANACAK
            p.Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            p.Status = true;
            _message2Service.TAdd(p);
            return RedirectToAction("SendBox");
        }
    }
}

SigortaApp/Controllers/MessageController.cs
using SigortaApp.BL.Abstract;
using SigortaApp.BL.Concrete;
using SigortaApp.Entity.Concrete;
using SigortaApp.DAL.Concrete;
using SigortaApp.DAL.EntityFramework;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace SigortaApp.Web.Controllers
{
    public class MessageController : Controller
    {
        private readonly IMessage2Service _message2Service;
        private readonly Context _context;

        public MessageController(IMessage2Service message2Service, Context context)
        {
            _message2Service = message2Service;
            _context = context;
        }

        public IActionResult InBox()
        {
            var username = User.Identity.Name;
            var usermail = _context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = _context.Writers.Where(w => w.Mail == usermail).Select(y => y.Id).FirstOrDefault();
            var values = _message2Service.GetInboxListByWriter(writerId);
            return View(values);
        }

        public IActionResult SendBox()
        {
            var username = User.Identity.Name;
            var usermail = _context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = _context.Writers.Where(w => w.Mail == usermail).Select(y => y.Id).FirstOrDefault();
            var values = _message2Service.GetSendboxListByWriter(writerId);
            return View(values);
        }

        public IActionResult MessageDetails(int id)
        {
            var value = _message2Service.TGetById(id);
            return View(value);
        }

        [HttpGet]
        public IActionResult SendMessage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SendMessage(Message2 message2)
        {
            var username = User.Identity.Name;
            var usermail = _context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerId = _context.Writers.Where(w => w.Mail == usermail).Select(y => y.Id).FirstOrDefault();
            message2.SenderId = writerId;
            message2.ReveiverId = 5;
            message2.Status = true;
            message2.Date = Convert.ToDateTime(DateTime.Now.ToShortDateString());
            _message2Service.TAdd(message2);
            return RedirectToAction("InBox");
        }
    }
}

SigortaApp/Views/Message/InBox.cshtml
@using SigortaApp.Entity.Concrete
@model List<Message2>
@{
    ViewData["Title"] = "InBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Gelen Kutusu</h1>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Gönderen</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.Id</th>
            <td>@item.Subject</td>
            <td>@item.SenderUser.Name</td>
            <td>@(((DateTime)item.Date).ToString("dd-MMM-yyyy"))</td>

            <td><a href="/Message/MessageDetails/@item.Id" class="btn btn-warning">Mesajı Aç</a></td>
        </tr>
    }
</table>
<a href="/Message/SendMessage/" class="btn btn-primary">Yeni Mesaj Oluştur</a>

SigortaApp/Views/Message/MessageDetails.cshtml
@model SigortaApp.Entity.Concrete.Message2

@{
    ViewData["Title"] = "MessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Mesaj Detay Sayfası</h1>
<br />
@Html.Label("Mesaj Id")
@Html.TextBoxFor(x =>x.Id,new {@class ="form-control"})
<br />
@Html.Label("Mesaj Başlığı")
@Html.TextBoxFor(x =>x.Subject,new {@class ="form-control"})
<br />
@Html.Label("Mesaj İçeriği")
@Html.TextAreaFor(x =>x.Details,20,3,new {@class ="form-control"})
<br />
<a href="/Message/InBox/" class="btn btn-success">Mesajlara Dön</a>

SigortaApp/Views/Message/SendBox.cshtml
@using SigortaApp.Entity.Concrete
@model List<Message2>
@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Giden Kutusu</h1>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.Id</th>
            <td>@item.Subject</td>
            <td>@item.ReceiverUser.Name</td>
            <td>@(((DateTime)item.Date).ToString("dd-MMM-yyyy"))</td>

            <td><a href="/Message/MessageDetails/@item.Id" class="btn btn-warning">Mesajı Aç</a></td>
        </tr>
    }
</table>
<a href="/Message/SendMessage/" class="btn btn-primary">Yeni Mesaj Oluştur</a>

SigortaApp/Views/Message/SendMessage.cshtml
@model SigortaApp.Entity.Concrete.Message2
@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Yeni Mesaj Oluştur</h1>
<br />
@using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
{
    @Html.Label("Alıcı")
    <input type="text" class="form-control">
    <br />
    @Html.Label("Konu")
    @Html.TextBoxFor(x => x.Subject, new {@class="form-control"})
    <br />
    @Html.Label("Mesajınız")
    @Html.TextAreaFor(x => x.Details, 15,3, new {@class="form-control"})
    <br />
    <button class="btn btn-info">Mesajı Gönder</button>

}